# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

R: Sim, conforme mostra a célula abaixo:

In [3]:
matrix = [[1, 2 ], [4, 5 ], [7, 8 ]]
matrix

[[1, 2], [4, 5], [7, 8]]

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [5]:
hsp70 = [21, 'He', 1, False]
h2b = [11, 'hi', 0, False]
cco1 = [30, 'cy', 1, False]
actin = [5, 'ac', 1, False]
ribosomal_rna = [17, '18', 2, False]

matriz_de_genes = [hsp70, h2b, cco1, actin, ribosomal_rna]
matriz_de_genes

[[21, 'He', 1, False],
 [11, 'hi', 0, False],
 [30, 'cy', 1, False],
 [5, 'ac', 1, False],
 [17, '18', 2, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [6]:
import numpy as np
matriz_de_genes_np = np.array(matriz_de_genes)
matriz_de_genes_np

array([['21', 'He', '1', 'False'],
       ['11', 'hi', '0', 'False'],
       ['30', 'cy', '1', 'False'],
       ['5', 'ac', '1', 'False'],
       ['17', '18', '2', 'False']], dtype='<U21')

## 4 – Recupere todos os itens do terceiro gene.

In [8]:
matriz_de_genes_np[2]

array(['30', 'cy', '1', 'False'], dtype='<U21')

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [11]:
for linha in matriz_de_genes_np:
    print('hu' in linha[1].lower())

False
False
False
False
False

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [ ]:
print(matriz_de_genes_np[1,1], matriz_de_genes_np [1,2])
print(matriz_de_genes_np[4,1], matriz_de_genes_np [4,2])

hi 0
18 2

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [31]:
import pandas as pd
lista_genes = ['Heat shock protein 70','histone H2B','cytochrome c oxidase subunit 1','actin','18S ribosomal RNA'] 

dic = {
    lista_genes[0]: hsp70,
    lista_genes[1]: h2b,
    lista_genes[2]: cco1,
    lista_genes[3]: actin,
    lista_genes[4]: ribosomal_rna
}


df_genes = pd.DataFrame(dic)
df_genes

,Heat shock protein 70,histone H2B,cytochrome c oxidase subunit 1,actin,18S ribosomal RNA
0,21,11,30,5,17
1,He,hi,cy,ac,18
2,1,0,1,1,2
3,False,False,False,False,False

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [33]:
df_genes.loc[[0,2]]

,Heat shock protein 70,histone H2B,cytochrome c oxidase subunit 1,actin,18S ribosomal RNA
0,21,11,30,5,17
2,1,0,1,1,2

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [36]:
df_genes.loc[3, [df_genes.columns[0], df_genes.columns[2]]]

Heat shock protein 70             False
cytochrome c oxidase subunit 1    False
Name: 3, dtype: object

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [59]:
df = pd.read_csv('data.csv')

n_entradas = len(df)

classes = list(df.dtypes)

n_por_classe = list(df.count())

colunas = df.iloc[:, [0,3,8]]

medias = list(colunas.mean())
desvios = list(colunas.std())   
q3 = list(colunas.quantile(0.75))

resultado = {

    'n_entradas': n_entradas,
    'classes': classes, 
    'n_por_classe': n_por_classe,
    'medias': medias,
    'desvios': desvios,
    'q3': q3

}  

print(resultado)

{'n_entradas': 36634, 'classes': [dtype('int64'), <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('int64'), dtype('float64'), dtype('float64'), <StringDtype(storage='python', na_value=nan)>, <StringDtype(storage='python', na_value=nan)>, dtype('int64')], 'n_por_classe': [36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634], 'medias': [548661.9371894961, 731478.0068460993, 2571004.0973420865], 'desvios': [259912.9264939009, 17523003.588415086, 20367766.569178067], 'q3': [774252.0, 0.0, 1128871.1824999999]}